import {
  Injectable,
  NotFoundException,
  InternalServerErrorException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createHash, createHmac, randomBytes } from 'crypto';
import { PrismaService } from '../prisma/prisma.service';
import { CreateEventDto } from './dto/create-event.dto';
import { UpdateEventDto } from './dto/update-event.dto';

@Injectable()
export class EventsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly config: ConfigService,
  ) {}

  /**
   * Generates a SHA-256 hash for the QR code.
   * Includes random salt to ensure uniqueness even for identical events.
   */
  private generateQrHash(title: string): string {
    const salt = randomBytes(16).toString('hex');
    const data = `${title}-${Date.now()}-${salt}`;
    return createHash('sha256').update(data).digest('hex');
  }

  /**
   * Generates an HMAC signature for the given hash.
   * Used to verify that a QR code was generated by our system.
   */
  generateSignature(hash: string): string {
    const secret = this.config.get<string>('QR_HMAC_SECRET');
    if (!secret) {
      throw new InternalServerErrorException('HMAC secret is not configured');
    }
    return createHmac('sha256', secret).update(hash).digest('hex').slice(0, 16);
  }

  /**
   * Verifies that a signature matches the expected HMAC for a given hash.
   */
  verifySignature(hash: string, signature: string): boolean {
    const expected = this.generateSignature(hash);
    return expected === signature;
  }

  async create(dto: CreateEventDto) {
    const qrHash = this.generateQrHash(dto.title);

    const event = await this.prisma.event.create({
      data: {
        title: dto.title,
        description: dto.description,
        dateTime: new Date(dto.dateTime),
        location: dto.location,
        organizer: dto.organizer,
        category: dto.category,
        ticketPrice: dto.ticketPrice,
        qrHash,
      },
    });

    return {
      ...event,
      ticketPrice: Number(event.ticketPrice),
      signature: this.generateSignature(event.qrHash),
    };
  }

  async findAll() {
    const events = await this.prisma.event.findMany({
      orderBy: { createdAt: 'desc' },
    });

    return events.map((event) => ({
      ...event,
      ticketPrice: Number(event.ticketPrice),
      signature: this.generateSignature(event.qrHash),
    }));
  }

  async findOne(id: number) {
    const event = await this.prisma.event.findUnique({ where: { id } });

    if (!event) {
      throw new NotFoundException(`Event with ID ${id} not found`);
    }

    return {
      ...event,
      ticketPrice: Number(event.ticketPrice),
      signature: this.generateSignature(event.qrHash),
    };
  }

  async findByHash(hash: string, signature: string) {
    // Verify HMAC signature to confirm the QR was generated by our system
    if (!this.verifySignature(hash, signature)) {
      throw new NotFoundException('Invalid or tampered QR code');
    }

    const event = await this.prisma.event.findUnique({
      where: { qrHash: hash },
    });

    if (!event) {
      throw new NotFoundException('Event not found for this QR code');
    }

    return {
      ...event,
      ticketPrice: Number(event.ticketPrice),
    };
  }

  async update(id: number, dto: UpdateEventDto) {
    // Check the event exists first
    await this.findOne(id);

    const event = await this.prisma.event.update({
      where: { id },
      data: {
        ...(dto.title && { title: dto.title }),
        ...(dto.description && { description: dto.description }),
        ...(dto.dateTime && { dateTime: new Date(dto.dateTime) }),
        ...(dto.location && { location: dto.location }),
        ...(dto.organizer && { organizer: dto.organizer }),
        ...(dto.category && { category: dto.category }),
        ...(dto.ticketPrice !== undefined && { ticketPrice: dto.ticketPrice }),
      },
    });

    return {
      ...event,
      ticketPrice: Number(event.ticketPrice),
      signature: this.generateSignature(event.qrHash),
    };
  }

  async remove(id: number) {
    await this.findOne(id);

    await this.prisma.event.delete({ where: { id } });

    return { message: `Event with ID ${id} has been deleted` };
  }
}
